<h1>DeleteController::deleteAction()</h1>
<p>
    Are you sure that you want to delete
    '<?php echo $this->escapeHtml($this->task->getTitle()); ?>' by
    '<?php echo $this->escapeHtml($this->task->getDescription()); ?>'?
</p>
<form action="<?php echo $this->url('task/delete', array(), true) ?>" method="post">
    <input type="submit" name="delete_confirmation" value="yes">
    <input type="submit" name="delete_confirmation" value="no">
</form>